Fix CSV export for `utf8mb4` encoding
On MySQL, in order to store Emoji in the database, one must use
`utf8mb4` encoding. Yet, this encoding was not present in the list of
`UTF8_ENCODINGS`, so the export fails with

    ArgumentError: unknown encoding name - utf8mb4